import { Header } from '@/components/Header';
import { AuthProvider } from '@/contexts/loginContext';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <AuthProvider>
            <html lang='en' className='bg-makerBg text-black'>
                <body className={inter.className}>
                    <Header />
                    {children}
                </body>
            </html>
        </AuthProvider>
    );
}
